kind = "web"
previewPath = "/"
title = "Nearz"
version = "1.0.0"
id = "artifacts/nearz"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19269

[services.development]
run = "pnpm --filter @workspace/nearz run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nearz", "run", "build" ]
publicDir = "artifacts/nearz/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19269"
BASE_PATH = "/"
